---
- name: Create the Sonarr container
  docker_container:
    name: sonarr
    image: linuxserver/sonarr
    restart_policy: unless-stopped
    pull: true
    ports:
      - "8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/sonarr/config:/config
      - /volume1/Downloads/TV Shows:/tv
      - /volume1/Downloads/bittorrent:/downloads
