version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ombi_proxy.conf:/etc/nginx/ombi_proxy.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/zfadli/my_pelican:/my_pelican
    restart: always
    ports:
      - 80:80
      - 443:443

