version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxy_ombi.conf:/etc/nginx/proxy_ombi.conf
      - ./transmission.conf:/etc/nginx/transmission.conf
      - ./media.conf:/etc/nginx/media.conf
      - ./static.conf:/etc/nginx/static.conf
      - ./hass.conf:/etc/nginx/hass.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/zfadli/my_pelican:/my_pelican
    restart: always
    ports:
      - 80:80
      - 443:443

