version: "3.5"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ./plex:/config
      - ${TVDIR}:/tv
      - ${MOVIESDIR}:/movies
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./sonarr:/config
      - ${DLDIR}/complete:/downloads/complete
      - ${TVDIR}:/tv
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      #- jackett
      - sabnzbd
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./radarr:/config
      - ${DLDIR}/complete:/downloads/complete
      - ${MOVIESDIR}:/movies
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      #- jackett
      - sabnzbd

  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./sabnzbd:/config
      - ${DLDIR}:/downloads
    ports:
      - 8080:8080
      - 9090:9090
    restart: unless-stopped

  nzbhydra2:
    image: ghcr.io/linuxserver/nzbhydra2
    container_name: nzbhydra2
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./nzbhydra2:/config
      - ${DLDIR}:/downloads #optional
    ports:
      - 5076:5076
    restart: unless-stopped

  readarr:
    container_name: readarr
    image: hotio/readarr:nightly
    ports:
      - "8787:8787"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
    volumes:
        - ./readarr:/config
        - ${DLDIR}/complete:/downloads/complete
        - ${BOOKSDIR}:/books
    restart: unless-stopped
    depends_on:
      - sabnzbd

  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      #- PASSWORD= #optional
      #- CLI_ARGS= #optional
    volumes:
      - ./calibre:/config
      - ${BOOKSDIR}:/books
      - ${DLDIR}/complete:/downloads/complete # for mannuallly adding books downloaded from sabnzbd
    ports:
      - 8082:8080 # 8080 taken by sabnzbd
      - 8081:8081
    restart: unless-stopped

  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ./calibre-web:/config
      - ${BOOKSDIR}:/books
    ports:
      - 8083:8083
    restart: unless-stopped

  # Tracker and downloader for torrent support
  #jackett:
    #image: linuxserver/jackett
    #container_name: jackett
    #restart: unless-stopped
    #ports:
      #- 9117:9117
    #environment:
      #- PUID=${PUID}
      #- PGID=${PGID}
    #volumes:
      #- ./jackett:/config
      #- ${DLDIR}/complete:/downloads
      #- /etc/localtime:/etc/localtime:ro
  #transmission:
    #image: linuxserver/transmission
    #container_name: transmission
    #environment:
      #- PUID=${PUID}
      #- PGID=${PGID}
      #- TZ=${TZ}
      ##- TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    #volumes:
      #- ./tansmission:/config
      #- ${DLDIR}:/downloads
    #ports:
      #- 9091:9091
      #- 51413:51413
      #- 51413:51413/udp
    #restart: unless-stopped
