version: "3.5"
services:

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: ${PUID}:${PGID}
    network_mode: "host"
    volumes:
      - ./jellyfin:/config
      - ./jellyfin-cache:/cache
      - ${TVDIR}:/media/tv
      - ${MOVIESDIR}:/media/movies
      - /etc/localtime:/etc/localtime:ro
    restart: "unless-stopped"

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./sonarr:/config
      - ${DLDIR}/complete:/downloads/complete
      - ${TVDIR}:/tv
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - jackett
      - transmission
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./radarr:/config
      - ${DLDIR}/complete:/downloads/complete
      - ${MOVIESDIR}:/movies
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - jackett
      - transmission
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    restart: unless-stopped
    ports:
      - 3579:3579
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./ombi:/config
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - radarr
      - sonarr

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./jackett:/config
      - ${DLDIR}/complete:/downloads
      - /etc/localtime:/etc/localtime:ro

  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./sabnzbd:/config
      - ${DLDIR}:/downloads #optional
    ports:
      - 8080:8080
      - 9090:9090
    restart: unless-stopped


  readarr:
    container_name: readarr
    image: hotio/readarr:nightly
    ports:
      - "8787:8787"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
    volumes:
        - ./readarr:/config
        - ${DLDIR}/complete:/downloads/complete
        - ${BOOKSDIR}:/books
    ports:
      - 5299:5299
    restart: unless-stopped
    depends_on:
      - transmission

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      #- TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    volumes:
      - ./tansmission:/config
      - ${DLDIR}:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
