- id: '1664920085635'
  alias: Co2 1000
  description: ''
  trigger:
  - type: carbon_dioxide
    platform: device
    device_id: 643cb0a9be7a1ce76dbb0f743f7ecf23
    entity_id: sensor.chaville_nws_v5_beta_co2
    domain: sensor
    above: 2000
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.speaker
      message: C O2 has reached {{ states('sensor.chaville_nws_v5_beta_co2') | round(0)
        }} ppm downstairs
  mode: single
