- id: '1643823699845'
  alias: CO2 too high
  description: ''
  trigger:
  - type: carbon_dioxide
    platform: device
    device_id: bff5de7a2b32f197ecd5b89b37d9cfc4
    entity_id: sensor.netatmo_issy_indoor_co2
    domain: sensor
    above: 3000
  condition: []
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.speaker
      message: See o 2 is too high
  mode: single
- id: '1647990454316'
  alias: potential ha 1
  description: ''
  trigger:
  - platform: device
    device_id: 33f78f982b880273378b252ad07ae0a2
    domain: homekit_controller
    type: button1
    subtype: single_press
  condition: []
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.speaker
      message: home button pressed
  mode: single
- id: '1647990607677'
  alias: Certificate expired
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.cert_expiry_timestamp_hass_zakariafadli_com
  condition: []
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.speaker
      message: Renew certificate for hassio
  mode: single

alias: GRDF get data
description: 'Récupérer les données de consommation'
trigger:
  - platform: time_pattern
    hours: '20'
    minutes: /30
    seconds: '00'
  - platform: time_pattern
    hours: '21'
    minutes: /30
    seconds: '00'
  - platform: time_pattern
    hours: '22'
    minutes: /30
    seconds: '00'
  - platform: time_pattern
    hours: '23'
    minutes: /10
    seconds: '00'
condition:
  - condition: numeric_state
    entity_id: sensor.grdf_consommation_gaz
    below: '-0.5'
action:
  - service: shell_command.grdf_get_data
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: homeassistant.update_entity
    target:
      entity_id:
        - sensor.grdf_consommation_gaz
mode: single

alias: GRDF reset
description: 'Effacer données de consommation journalières'
trigger:
  - platform: time
    at: '23:56'
condition: []
action:
  - service: shell_command.grdf_delete_data
    data: {}
  - delay: '00:01:00'
  - service: homeassistant.update_entity
    target:
      entity_id:
        - sensor.grdf_consommation_gaz
mode: single
