---
- name: Ensures config directory exists
  file:
    path: "/volume1/docker/{{ item }}/config"
    state: directory
  loop:
     - jackett
     - ombi
     - organizr
     - radarr
     - sonarr
     - tautulli
     - transmission
