version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/raspberrypi4-homeassistant:latest
    volumes:
      # Local path where your home assistant config will be stored
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/udev:/run/udev:ro
    restart: unless-stopped
    network_mode: host
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/ttyUSB0
