bridge:
  name: Bifrost
  mac: e4:5f:01:33:55:5e
  timezone: Europe/Paris
  ipaddress: 192.168.1.11
  netmask: 255.255.255.0
  gateway: 192.168.1.255


  # HTTP port for emulated bridge
  #
  # beware: most client programs do NOT support non-standard ports.
  # This is for advanced users (e.g. bifrost behind a reverse proxy)
  http_port: 80

  # HTTPS port for emulated bridge
  #
  # beware: most client programs do NOT support non-standard ports.
  # This is for advanced users (e.g. bifrost behind a reverse proxy)
  https_port: 443

  # DTLS port for emulated bridge (Hue Entertainment streaming)
  #
  # beware: client programs do NOT support non-standard ports.
  # For advanced users (e.g. bifrost behind a port forwarded firewall)
  entm_port: 2100


z2m:
  server1:
    url: ws://0.0.0.0:8456

