---
- name: Create the Ouroboros container
  docker_container:
    name: ouroboros
    image: pyouroboros/ouroboros
    restart_policy: unless-stopped
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    env:
      SELF_UPDATE: "true"
      CLEANUP: "true"
      CRON: "0 5 * * *"
      NOTIFIERS: "{{ NOTIFICATION_SLACK_HOOK_URL }}"
