
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  # For extra security set this to only accept connections on localhost if NGINX is on the same machine
  # Uncommenting this will mean that you can only reach Home Assistant using the proxy, not directly via IP from other clients.
  # server_host: 127.0.0.1
  use_x_forwarded_for: true
  # You must set the trusted proxy IP address so that Home Assistant will properly accept connections
  trusted_proxies:
          # Local IP for cloudflare tunnel
          - 192.168.1.11


# Text to speech
tts:
  - platform: edge_tts
    language: en-GB-LibbyNeural

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes

google_assistant:
  project_id: oiassistant
  service_account: !include oiassistant-secrets.json
  report_state: true
  expose_by_default: false
  exposed_domains:
  entity_config:

homeassistant:
  external_url: https://hass.zakariafadli.com/
