
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  # For extra security set this to only accept connections on localhost if NGINX is on the same machine
  # Uncommenting this will mean that you can only reach Home Assistant using the proxy, not directly via IP from other clients.
  # server_host: 127.0.0.1
  use_x_forwarded_for: true
  # You must set the trusted proxy IP address so that Home Assistant will properly accept connections
  trusted_proxies:
          # Local IP for cloudflare tunnel
          - 192.168.1.11


# Text to speech
tts:
  - platform: edge_tts
    language: en-GB-LibbyNeural

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  external_url: https://hass.zakariafadli.com/

template:
  - sensor:
      # Minutes until the very next bus 171
      - name: "minutes_to_next_bus"
        unique_id: minutes_to_next_bus
        unit_of_measurement: "min"
        state: >
          {% set ts = states('sensor.bus_next_0') %}
          {% if ts not in ['unknown','unavailable',''] %}
            {{ ((as_timestamp(ts) - as_timestamp(now())) / 60) | round(0, default=0) }}
          {% else %}
            unknown
          {% endif %}

      # Minutes until the very next train on line L
      - name: "minutes_to_next_train_l"
        unique_id: minutes_to_next_train_l
        unit_of_measurement: "min"
        state: >
          {% set ts = states('sensor.l_line_next_0') %}
          {% if ts not in ['unknown','unavailable',''] %}
            {{ ((as_timestamp(ts) - as_timestamp(now())) / 60) | round(0, default=0) }}
          {% else %}
            unknown
          {% endif %}
